// The large synthetic conversation behind the performance-budget laws
// (TVC-160/161): a long, realistic TeaFlask support thread —
// prose, reasoning, annotated and unannotated operations, failures,
// cancellations — generated by index arithmetic alone, so every run
// and every machine sees byte-identical input. No randomness, no
// clock: determinism is what makes the DOM ceiling a real number.

import type { Message } from "@ag-ui/core";

import type { MarkerAnchorsSnapshot } from "../../src/core/connection-epoch";
import type { ToolCallDisplay } from "../../src/core/tool-call-display";

export const SYNTHETIC_TURN_COUNT = 40;

/** Rows per generated turn: one user row, one reasoning row, two tool
 *  rows, one assistant prose row. Kept in lockstep with the generator
 *  below by construction — TVC-161 asserts the product. */
export const SYNTHETIC_ROWS_PER_TURN = 5;

const TOOL_NAMES = [
  "docs_search",
  "action__create-support-ticket",
  "read_page",
  "action__update-subscription",
];

const TOPICS = [
  "steeping sencha",
  "kettle descaling",
  "gyokuro storage",
  "cold brew ratios",
  "teapot warranty",
];

export function syntheticMessagesOf(): Message[] {
  const messages: Message[] = [];
  for (let turn = 0; turn < SYNTHETIC_TURN_COUNT; turn += 1) {
    const topic = TOPICS[turn % TOPICS.length];
    messages.push({
      id: `u${String(turn)}`,
      role: "user",
      content: `Can you check the ${topic} guidance for turn ${String(turn + 1)}?`,
    });
    messages.push({
      id: `th${String(turn)}`,
      role: "reasoning",
      content:
        `The member is asking about ${topic}. Check the documented numbers ` +
        "before answering so the figures are theirs, not mine.",
    });
    messages.push({
      id: `a${String(turn)}`,
      role: "assistant",
      content: "",
      toolCalls: [0, 1].map((call) => ({
        id: `t${String(turn)}-${String(call)}`,
        type: "function" as const,
        function: {
          name: TOOL_NAMES[(turn + call) % TOOL_NAMES.length],
          arguments: JSON.stringify({ query: topic, page: turn + call }),
        },
      })),
    });
    for (const call of [0, 1]) {
      messages.push({
        id: `r${String(turn)}-${String(call)}`,
        role: "tool",
        toolCallId: `t${String(turn)}-${String(call)}`,
        content:
          `[${topic}#${String(call)}] Documented answer ${String(turn)}.` +
          `${String(call)} — the guide's own figure, verbatim.`,
      });
    }
    messages.push({
      id: `p${String(turn)}`,
      role: "assistant",
      content:
        `The **${topic}** guidance holds for case ${String(turn + 1)}: the ` +
        "documented figure matches what the member is seeing, so no drift " +
        "correction is needed here.",
    });
  }
  return messages;
}

export function syntheticAnchorsOf(): MarkerAnchorsSnapshot {
  const errors = new Map<string, string>();
  const cancels = new Set<string>();
  const displays = new Map<string, ToolCallDisplay>();
  for (let turn = 0; turn < SYNTHETIC_TURN_COUNT; turn += 1) {
    // Every fifth turn fails its first call; the next one cancels it —
    // the settled ladder stays exercised at scale.
    if (turn % 5 === 3) {
      errors.set(`t${String(turn)}-0`, "The guide took too long to respond.");
    }
    if (turn % 5 === 4) {
      cancels.add(`t${String(turn)}-0`);
    }
    // Every other turn's first call arrives annotated.
    if (turn % 2 === 0) {
      displays.set(`t${String(turn)}-0`, {
        progressText: `Checking the ${TOPICS[turn % TOPICS.length]} guide…`,
        completeText: `Checked the ${TOPICS[turn % TOPICS.length]} guide`,
      });
    }
  }
  return {
    resumeAnchors: new Map(),
    turnFailedAnchors: new Map(),
    toolRefusalAnchors: new Map(),
    toolErrorAnchors: errors,
    toolCancelAnchors: cancels,
    toolOffloadAnchors: new Set(),
    toolCallDisplayAnchors: displays,
    toolSchemaAnchors: new Map(),
    subagentDeliveryAnchors: new Map(),
    blockTimingAnchors: new Map(),
    turnUsageAnchors: new Map(),
    memoryProvenanceAnchors: new Map(),
    memoryAttributionAnchors: new Map(),
  };
}
